### ISSUE TITLE
Fix crash in .csv export

### ISSUE THREAD

**Issue by Gear61** [Gear61/Simple-Flashcards#109]
Object.requireNotNull is crashing for some reason? People don't have Java 7??? Let's see if we can hack it.

**Comment by nogipx** [comment]
https://github.com/osiegmar/FastCSV/issues/3#issuecomment-361359273

As said this dude and docs, method toPath() appears in Android since API 26.
I sent you syslog.

**Comment by Gear61** [comment]
@nogipx Yep, I found that issue just now as I was digging around in his code. Working on a fix!
