### ISSUE TITLE
New Logo For Flash Cards

### ISSUE THREAD

**Issue by zularizal** [Gear61/Simple-Flashcards#12]
Hi, I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo & icons. What do you think?

**Comment by Gear61** [comment]
@zularizal Sure? Any ideas on what kind of icon you're going to design? I can credit you for your work in the Play Store listing and somewhere in the app itself on the settings page.

**Comment by zularizal** [comment]
Hi @Gear61 , how do you think, which one do you like? If you want change please please let me know.

![logo](https://user-images.githubusercontent.com/38547278/40263207-4bb3c38c-5b39-11e8-978c-73ddacbb13ec.png)

**Comment by Gear61** [comment]
@zularizal Oh wow, these look **incredible**. I especially like #2. Can you make them adaptive as well so they'll change properly on Android Oreo (square, rounded square, squircle, teardrop)? I'm happy to include permanent links to whatever website/portfolio you have in the Play Store listing and app itself as well. I can write up a nice page for you in the settings.

**Comment by zularizal** [comment]
Thanks for your offer, I have not created a portfolio yet, but you can enter my github link

Of course it can be adaptive, wait a moment I will upload the logo to the drive.

**Comment by zularizal** [comment]
Hi @Gear61 , I have uploaded the logo to drive, here is the link
https://drive.google.com/open?id=1mUjgdgQOSfo39k6uUbhfryYltVfZSkkE

And also I have sent a pull request, please check  #17
