### ISSUE TITLE
Cannot Resolve Symbol

### ISSUE THREAD

**Issue by rhayes2** [Gear61/Simple-Flashcards#56]
![capture](https://user-images.githubusercontent.com/43277456/47573964-91938800-d90c-11e8-896e-bfd650f95a6d.PNG)

Does the clientId come from ApiConstants?
Once I replace it with ApiConstants.CLIENT_ID_KEY it works.

**Comment by Gear61** [comment]
@rhayes2 I don't commit my Quizlet API key to GitHub. You can get your own at Quizlet.com, create a file named QuizletAuthConstants, and place your key there.
