### ISSUE TITLE
Internationalization - Spanish

### ISSUE THREAD

**Issue by UnsolvedCypher** [Gear61/Simple-Flashcards#87]
I would like to use this app in a Spanish to English classroom. @Gear61, would you be interested in help with translating the UI to Spanish? Android already has a built-in mechanism for internationalization [here](https://developer.android.com/guide/topics/resources/localization), so most of the work would be abstracting out the string literals. I would be happy to provide the Spanish translations.

Thoughts?

**Comment by Gear61** [comment]
Hi @UnsolvedCypher, thanks for opening this issue! I'm happy to translate this app into Spanish; all of my UI strings are in resource files already, so it should be straightforward. All we need to do is create Spanish locale versions of all the string resources files I have. I'm actually semi-fluent in Spanish (studied it for 5 years), so I can roughly double check whatever translations you provide as well. How do you want to go about this?

**Comment by UnsolvedCypher** [comment]
That is great to hear! I didn't realize the strings were in resource files already, so that does make things significantly easier. If you you could set up the directory structure that's needed in another branch, I can start translating the XML files in the meantime and I think we should be off to a good start. Thanks for the quick reply!

**Comment by Gear61** [comment]
Oh wow, thank you for the even quicker reply @UnsolvedCypher!

This is my first time translating an app, so apologies for any future dumb mistakes I make haha. Anyways, I've created a branch called spanish-translation with es versions of all the value files. You can see all the files I added in this commit: https://github.com/Gear61/Simple-Flashcards/commit/47636c620a7fa4d7d70febc5be52fd34dbc369cf

So I think if you just swap out all the copy-pasta-ed English values in those values-es files with the actual Spanish translations, we should be good! From here, I think the way to go if for you to fork this repository, change your version of the spanish-translation branch with the proper translations, and then submit a pull request of your spanish-translation branch in your repo into the spanish-translation branch of this repo. Once we merge the PR, I'll merge spanish-translation into master and push out a new Spanish-enabled build!

**Comment by Gear61** [comment]
Also, Quizlet isn't accepting developer applications anymore, so you'll need to follow the instructions in the README and just create a QuizletAuthConstants value of "" if you want to compile the app. I'm also fine just accepting an untested PR; we're not changing any real code.
